# Generated by Django 2.0.5 on 2018-05-31 06:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geo_proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('coverage', models.FloatField()),
                ('date_of_capture', models.DateField(auto_now=True)),
                ('sensor_name', models.CharField(max_length=250)),
                ('data_density', models.FloatField()),
                ('fva', models.CharField(max_length=250)),
                ('fha', models.CharField(max_length=250)),
                ('horizontal_datum', models.CharField(max_length=250)),
                ('map_projection', models.CharField(max_length=250)),
                ('vertical_datum', models.CharField(max_length=250)),
                ('geoid_model', models.CharField(max_length=250)),
                ('scan_angle', models.CharField(max_length=250)),
                ('track_point_spacing_ratio', models.CharField(max_length=250)),
                ('flight_overlap', models.FloatField()),
                ('environmental_conditions', models.CharField(max_length=250)),
                ('intensity', models.BooleanField(default='False')),
                ('intensity_value', models.FloatField()),
                ('height_of_flight', models.FloatField()),
                ('velocity_of_flight', models.FloatField()),
                ('nature_of_aerial_platform', models.IntegerField()),
                ('horizontal_accuracy', models.CharField(max_length=250)),
                ('project_manager', models.CharField(max_length=250)),
                ('user_department', models.CharField(max_length=250)),
                ('multiple_returns', models.BooleanField(default='False')),
                ('number_of_returns', models.FloatField()),
                ('waveform_captured', models.BooleanField(default='False')),
                ('kml_file', models.FileField(upload_to='')),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
