# Generated by Django 2.0.5 on 2018-05-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoproj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='geo_proj',
            new_name='Air_Lidar',
        ),
    ]
