# Generated by Django 2.0.5 on 2018-05-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoproj', '0005_dem_intensity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orthophoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ortho', models.CharField(max_length=250)),
                ('coverage', models.FloatField()),
                ('date_of_capture', models.DateField(auto_now=True)),
                ('file_Format', models.CharField(max_length=250)),
                ('gsd', models.FloatField()),
                ('true_colour', models.BooleanField(default=True)),
                ('false_colour', models.BooleanField(default=False)),
                ('collection_condition', models.CharField(max_length=1000)),
                ('horizontal_datum', models.CharField(max_length=250)),
                ('vertical_datum', models.CharField(max_length=250)),
                ('geoid_model', models.CharField(max_length=250)),
                ('map_projection', models.CharField(max_length=250)),
                ('horizontal_accuracy', models.CharField(max_length=250)),
                ('radiometric_resolution', models.CharField(max_length=250)),
                ('orthorectification_technique', models.CharField(max_length=250)),
                ('data_source1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geoproj.Air_Lidar')),
            ],
        ),
    ]
